[build]
  base = "web"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  VUE_APP_API_URL = "https://beekeper-d0e3.onrender.com/api"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://beekeper-d0e3.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
