[build]
  base = "/web"
  command = "npm install webpack@4 webpack-cli@4 @babel/core @babel/eslint-parser --save-dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  VUE_APP_API_URL = "https://beekeper-d0e3.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
