# 웹 프론트엔드(관리자용) 배포 설정
[build]
  command = "cd web && npm install && npm run build"
  publish = "web/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./web/"

# 모바일 앱 배포를 위한 별도 사이트 설정
# 이 설정은 Netlify UI에서 새 사이트를 만들 때 사용합니다
[context.app]
  command = "cd app && npm install && npm run build"
  publish = "app/dist"

# 개발 환경 설정 (deploy-preview, branch-deploy)
[context.deploy-preview]
  command = "cd web && npm install && npm run build"
  publish = "web/dist"

# 웹 관리자용 프론트엔드에 대한 추가 설정
[context.production.environment]
  NODE_VERSION = "16"

# 기사용 앱을 위한 추가 설정
[context.app.environment]
  NODE_VERSION = "16"

# SPA를 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수 설정
[build.environment]
  NODE_VERSION = "16.x"
  VUE_APP_API_URL = "https://beekeper-d0e3.onrender.com"
  NODE_ENV = "production"

# 캐시 설정
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 빌드 플러그인 설정
[[plugins]]
  package = "@netlify/plugin-cache-core"
