# 웹 프론트엔드(관리자용) 배포 설정
[context.production]
  # production 브랜치의 기본 설정
  command = "cd web && npm install && npm run build"
  publish = "web/dist"

# 모바일 앱 배포를 위한 별도 사이트 설정
# 이 설정은 Netlify UI에서 새 사이트를 만들 때 사용합니다
[context.app]
  command = "cd app && npm install && npm run build"
  publish = "app/dist"

# 개발 환경 설정 (deploy-preview, branch-deploy)
[context.deploy-preview]
  command = "cd web && npm install && npm run build"
  publish = "web/dist"

# 웹 관리자용 프론트엔드에 대한 추가 설정
[context.production.environment]
  NODE_VERSION = "16"

# 기사용 앱을 위한 추가 설정
[context.app.environment]
  NODE_VERSION = "16"

# SPA를 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
