# Render 배포 명세 파일 (Blueprint)
services:
  - type: web
    name: beekeper-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: CORS_ORIGIN
        value: https://beekeper.netlify.app
# 필요한 데이터베이스는 Render.com UI에서 직접 생성하거나
# MongoDB Atlas를 사용하는 것이 좋습니다.
// web/.env.production
VUE_APP_API_URL=https://beekeper-d0e3.onrender.com
VUE_APP_MAP_API_KEY=your_map_api_key

// web/src/api/config.js
import axios from 'axios';

const api = axios.create({
  baseURL: process.env.VUE_APP_API_URL,
  timeout: 5000,
  headers: {
    'Content-Type': 'application/json'
  }
});

// 토큰 인터셉터 추가
api.interceptors.request.use(config => {
  const token = localStorage.getItem('token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

export default api;
