[build]
  base = "web"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VUE_APP_API_URL = "https://api.example.com"
  NODE_VERSION = "16.13.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
