[build]
  command = "npm install && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  VUE_APP_API_URL = "https://beekeper-d0e3.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
