[build]
  base = "web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.x"
  VUE_APP_API_URL = "https://beekeper-d0e3.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
