[build]
  base = "."
  command = "npm install image-webpack-loader webpack@4 @babel/core @babel/eslint-parser --save-dev && sed -i 's|// web/src/assets/scss/variables.scss|/* CSS 변수 파일 임포트 */|g' src/assets/css/global.css && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  VUE_APP_API_URL = "https://beekeper-d0e3.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
